version: '3.1'

services:
  blog_strapi_api:
    container_name: blog_strapi_api
    hostname: blog_strapi_api
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog-strapi
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - .postgresql/blog_strapi_api:/var/lib/postgresql/data/pgdata
    ports:
      - 5434:5432